### ISSUE TITLE
The NoCAN event protocol over TCP/IP

### ISSUE THREAD

**Issue by hounded** [omzlo/omzlo.github.io#1]
Hi am I reading it wrong but is there no publish interface for the TCP/IP event protocol?

**Comment by omzlo** [comment]
A NoCAN "publish" will translate into a [ChannelUpdateEvent](https://github.com/omzlo/omzlo.github.io/blob/master/nocan/nocan-event-protocol.md#channelupdateevent-9) with status 1.  
 The documentation was indeed not clear about that so we updated it just now.
